# Application name
spring.application.name=patient-service
spring.profiles.active=dev
# Server configuration
server.port=8080
server.error.include-message=always
# Database configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
# Swagger/OpenAPI configuration
springdoc.swagger-ui.path=/api/v1/docs
springdoc.swagger-ui.use-root-path=true
# JWT
spring.app.jwtSecret=JWTSECRET
spring.app.expirationTimeMS=3600000
#1hour
spring.app.cookieName=TOKEN
grpc.server.security.enabled=false
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
#Oauth2 -client
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=
